module.exports = [
    {
      producer_id: 1,
      producer_name: "Christian Venier",
      producer_region: "France",
      producer_village: "Candé sur Beuvron, Loire",
      producer_image: "https://grandordinaire-4b0d635ecbc0.herokuapp.com/images/Christian_Venier.jpeg",
      producer_description: "In the eastern part of Touraine, specifically in Cheverny near the southern edge of Bois in Sologne, you'll find Christian Venier. This is where he refined his expertise in natural winemaking under the guidance of his cousins Thierry and Jean-Marie Puzelat from Clos du Tue Boeuf. Despite assisting with harvests for several seasons, it wasn't until the mid-90s that he crafted his inaugural vintage, 'Brin de Chevre.' Concurrently, he enrolled in the viticultural school of Amboise, where he discovered a lack of awareness among fellow students regarding organic farming practices.",
      producer_description2: "Throughout this period, Christian steadfastly adhered to his philosophy of crafting wine in a natural manner, resisting the prevailing trend that gained popularity across the country after the First World War, where many embraced mechanization. Remaining true to his farming roots, he continued to work the land organically across his roughly 6 hectares of vineyards. These vineyards were planted with a diverse array of grape varieties, including Pinot Noir, Gamay, Cabernet Franc, Pineau d’Aunis, Sauvignon Blanc, Chardonnay, Menu Pineau, and Chenin Blanc. The vines thrived in soils consisting of silica and clay, some interspersed with gravel and stones.",
      producer_description3: "Christian retained the role of a traditional farmer, eschewing interventionist practices in winemaking. His commitment to non-intervention extended to the fermentation process, allowing it to occur naturally under a loosely fitted cap. In the winery, he made use of resin-fiberglass, stainless steel, cement, and oak, all in large formats. Significantly, Christian refrained from making any additions or subtractions during the winemaking process, maintaining the purity and authenticity of his wines.",
    },
    {
        producer_id: 2,
        producer_name: "Pierre Bourlier",
        producer_region: "France",
        producer_village: "Ardèche",
        producer_image: "https://grandordinaire-4b0d635ecbc0.herokuapp.com/images/PierreBourlier.jpeg",
        producer_description: "Establishing his modest domaine in 2015, Pierre chose a location deep in the northern hills of Ardèche, just a short distance from St Joseph. Prior to this venture, he gained experience working with Gilles Azzoni and Domaine des Miquettes. Currently, he tends to 1.5 hectares of vines with plans for gradual expansion.",
        producer_description2: "Situated on the steep slopes of the Doux valley, the vineyards thrive on sandy granitic soils held in place by stone-wall terracing. Predominantly cultivating Gamay, with smaller plantings of Pinot Noir, Viognier, and Roussanne. The elevated location ensures cool evenings, preserving freshness following the daytime heat.",
        producer_description3: "The wines are elegant and perfumed and speak of a rising star in the region. Even in hot vintages the balance is wonderful. Sadly, however, they are not in abundance, but in the coming years Pierre plans to move to a new cellar and purchase a little more land and in the future we hope there will be a little more to go around.",
      },
      {
        producer_id: 3,
        producer_name: "Ca' de Noci",
        producer_region: "Italy",
        producer_village: "His mother had always taught him",
        producer_image: "https://grandordinaire-4b0d635ecbc0.herokuapp.com/images/CadeNociProd.jpg",
        producer_description: " In 1970, their father Vittorio, a devoted Agriculture teacher with a passion for vineyards, planted the initial vineyards. These vineyards featured a selection of indigenous grape varieties that have endured over the years, and they continue to preserve their genetic diversity through ongoing studies and research. Notable among them are Spergola, Malbo Gentile, and some rare ancient Lambrusco varieties.",
        producer_description2: "The journey into winemaking reached a milestone in 1993 when, in the garage beneath the house, the first bottle of Spergola vine was crafted, a Classic Method labeled as Riserva dei Fratelli. In 1998, they established the winery and initiated the production of various 'bottle fermented' sparkling wines using Spergola and Lambrusco varieties, such as Querciole and Sottobosco. That same year, they experimented with dried grapes of Moscato and Malvasia, resulting in the creation of Aresco.",
        producer_description3: "From the outset, their commitment has been to craft wines without the use of chemicals, and they have continued this practice into the future. Starting in 2001, they began producing still wines for aging, exclusively using local varieties like Gheppio and Nottediluna. After 2003, they acquired an additional one and a half hectares of vineyards on the high hills of Broletto, featuring chalky soil from the Appennini chain and hosting ancient vine varieties like Sgavetta and Malbo Gentile.",
      },
]