module.exports = [
    {
      product_id: 1,
      product_name: "La Plante Aux Loups 2022",
      product_region: "France",
      product_appellation: "Vin de France",
      product_image: "https://grandordinaire-4b0d635ecbc0.herokuapp.com/images/VenierB.jpg",
      product_description: "Extremely elegant, it's bright and balanced.",
      product_varietal: "Chardonnay",
      product_producer: "Christian Venier",
      product_vintage: "2022",
      producer_id: 1,
    },
    {
        product_id: 2,
        product_name: "Les Hauts de Madon",
        product_region: "France",
        product_appellation: "Vin de France",
        product_image: "https://grandordinaire-4b0d635ecbc0.herokuapp.com/images/VenierB2.jpg",
        product_description: "From a parcel named after the cuvée, with 50 years old vines. It's an amazing white wine, it's fresh and packed with fruit.",
        product_varietal: "Orbois (Menu Pineau)",
        product_producer: "Christian Venier",
        product_vintage: "2019",
        producer_id: 1,
      },
      {
        product_id: 3,
        product_name: "Clos des Carteries",
        product_region: "France",
        product_appellation: "Vin de France",
        product_image: "https://grandordinaire-4b0d635ecbc0.herokuapp.com/images/VenierR3.jpg",
        product_description: "It's glouglou yet nerdy. Fruity with bright acidity.",
        product_varietal: "Gamay, Pinot noir",
        product_producer: "Christian Venier",
        product_vintage: "2020",
        producer_id: 1,
      },
      {
        product_id: 4,
        product_name: "Querciole",
        product_region: "Emilia Romagna, Italy",
        product_appellation: "Emilia Bianco Frizzante igt Biologico",
        product_image: "https://grandordinaire-4b0d635ecbc0.herokuapp.com/images/CadeNociO.jpg",
        product_description: "The golden apple and baked brioche aromas of the bubbles pave the way for an exuberant palate of candied citrus, baked walnuts and pickled melon. ",
        product_varietal: "Spergola", 
        product_producer: "Ca' de Noci",
        product_vintage: "2020",
        producer_id: 3,
      },
      {
        product_id: 5,
        product_name: "Brine d'April",
        product_region: "Emilia Romagna, Italy",
        product_appellation: "Vino di Tavola",
        product_image: "https://grandordinaire-4b0d635ecbc0.herokuapp.com/images/CadeNociR2.jpg",
        product_description: "The Brine d’April cuvée offers lively fruit, spicy clove aromas, and a beautiful acidity that awakens the senses! A pure delight with meat-based starters, charcuteries, and cheeses.",
        product_varietal: "Malbo Gentile",
        product_producer: "Ca' de Noci",
        product_vintage: "2019",
        producer_id: 3,
      },
      {
        product_id: 6,
        product_name: "Notte di Luna",
        product_region: "Emilia Romagna , Italy",
        product_appellation: "Emilia Bianco igt Biologico",
        product_image: "https://grandordinaire-4b0d635ecbc0.herokuapp.com/images/CadeNociO2.jpg",
        product_description: "Inebriating florals of jasmine, citrus blossom and marzipan are joined by assertive fruit and briny tones with ripe persimmon, tinned peaches and lime zest.",
        product_varietal: "Moscato, Malvasia, Spergola",
        product_producer: "Ca' de Noci",
        product_vintage: "2019",
        producer_id: 3,
      },
      {
        product_id: 7,
        product_name: "Vaille que Vaille",
        product_region: "Ardèche, France",
        product_appellation: "Vin de France",
        product_image: "https://grandordinaire-4b0d635ecbc0.herokuapp.com/images/vailleQueVaille.jpeg",
        product_description: "This Gamay comes from a 60-year-old sandy granitic plot. After a week of whole bunch maceration and hand de-stemming, it undergoes a gentle 2-week skin fermentation. The result is a bright, elegant wine with red fruits and a pleasing mineral finish.",
        product_varietal: "Gamay",
        product_producer: "Pierre Bourlier",
        product_vintage: "2019",
        producer_id: 2,
      },
      
]