module.exports = [
    {
      product_id: 1,
      product_name: "La Plante Aux Loups 2022",
      product_region: "Loire, France",
      product_appellation: "Vin de France",
      product_image: "http://localhost:8080/images/VenierB.jpg",
      product_description: "Extremely elegant, it's bright and balanced.",
      product_varietal: "chardonnay",
      product_varietal2: "",
      product_varietal3: "",
      product_varietal4: "",
      producer_id: 1,
    },
    {
        product_id: 2,
        product_name: "Les Hauts de Madon",
        product_region: "Loire, France",
        product_appellation: "Vin de France",
        product_image: "http://localhost:8080/images/VenierB.jpg",
        product_description: "From a parcel named after the cuvée, with 50 years old vines. It's an amazing white wine, it's fresh and packed with fruit.",
        product_varietal: "Orbois (Menu Pineau)",
        producer_id: 1,
      },
      {
        product_id: 3,
        product_name: "Clos des Carteries",
        product_region: "Loire, France",
        product_appellation: "Vin de France",
        product_image: "http://localhost:8080/images/VenierR3.jpg",
        product_description: "It's glouglou yet nerdy. Fruity with bright acidity.",
        product_varietal: "Gamay",
        product_varietal2: "Pinot noir",
        producer_id: 1,
      },
      {
        product_id: 4,
        product_name: "Vaille que Vaille",
        product_region: "Ardèche, France",
        product_appellation: "Vin de France",
        product_image: "http://localhost:8080/images/vailleQueVaille.jpeg",
        product_description: "From a 60-year-old plot of Gamay planted on terraces of sandy granitic soil. Grapes were left in whole bunches to macerate for 1 week before being de-stemmed by hand and then fermented gently on the skins for another 2 weeks.This is about as perfumed as you can get from the Gamay grape — bright and elegant with little red fruits and a pleasing mineral finish.",
        product_varietal: "Gamay",
        producer_id: 2,
      },
      {
        product_id: 5,
        product_name: "Brine d'April",
        product_region: "Emilia Romagna, Italy",
        product_appellation: "Vino di Tavola",
        product_image: "http://localhost:8080/images/CadeNociR2.jpg",
        product_description: "The Brine d’April cuvée offers lively fruit, spicy clove aromas, and a beautiful acidity that awakens the senses! A pure delight with meat-based starters, charcuteries, and cheeses.",
        product_varietal: "Malbo Gentile",
        producer_id: 3,
      },
      {
        product_id: 6,
        product_name: "Notte di Luna",
        product_region: "Emilia Romagna , Italy",
        product_appellation: "Emilia Bianco igt Biologico",
        product_image: "http://localhost:8080/images/CadeNociO2.jpg",
        product_description: "Inebriating florals of jasmine, citrus blossom and marzipan are joined by assertive fruit and briny tones with ripe persimmon, tinned peaches and lime zest.",
        product_varietal: "Moscato",
        product_varietal2: "Malvasia",
        product_varietal3: "Spergola",
        producer_id: 3,
      },
      {
        product_id: 7,
        product_name: "Querciole",
        product_region: "Emilia Romagna, Italy",
        product_appellation: "Emilia Bianco Frizzante igt Biologico",
        product_image: "http://localhost:8080/images/CadeNociO.jpg",
        product_description: "The golden apple and baked brioche aromas of the bubbles pave the way for an exuberant palate of candied citrus, baked walnuts and pickled melon. ",
        product_varietal: "Spergola", 
        producer_id: 3,
      },
]