module.exports = [
    {
      product_id: 1,
      product_name: "His mother had always taught him",
      product_region: "His mother had always taught him",
      product_appellation: "His mother had always taught him",
      product_image: "http://localhost:8080/images/bmx.jpg",
      product_description: "His mother had always taught him",
      product_varietal: "His mother had always taught him",
      product_varietal2: "His mother had always taught him",
      product_varietal3: "His mother had always taught him",
      product_varietal4: "His mother had always taught him",
      producer_id: 1,
    },
    {
        product_id: 3,
        product_name: "His mother had always taught him",
        product_region: "His mother had always taught him",
        product_appellation: "His mother had always taught him",
        product_image: "http://localhost:8080/images/",
        product_description: "His mother had always taught him",
        product_varietal: "His mother had always taught him",
        product_varietal2: "His mother had always taught him",
        product_varietal3: "His mother had always taught him",
        product_varietal4: "His mother had always taught him",
        producer_id: 1,
      },
      {
        product_id: 2,
        product_name: "His mother had always taught him",
        product_region: "His mother had always taught him",
        product_appellation: "His mother had always taught him",
        product_image: "http://localhost:8080/images/bmx.jpg",
        product_description: "His mother had always taught him",
        product_varietal: "His mother had always taught him",
        product_varietal2: "His mother had always taught him",
        product_varietal3: "His mother had always taught him",
        product_varietal4: "His mother had always taught him",
        producer_id: 1,
      },
]